services:
  mysql:
    image: mysql:8.4
    container_name: aulafy_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: aulafy_db
      MYSQL_USER: aulafy_user
      MYSQL_PASSWORD: aulafy_pass
      MYSQL_ROOT_PASSWORD: root_pass_dev
    ports:
      - "3306:3306"
    volumes:
      - aulafy_mysql_data:/var/lib/mysql
      - ./database/mysql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/mysql/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pass_dev"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  aulafy_mysql_data:
