sonar.projectKey=aulafy
sonar.projectName=Aulafy
sonar.projectVersion=0.1.0
sonar.sourceEncoding=UTF-8

sonar.sources=backend/aulafy-api-nest/src,frontend/aulafy-web/src
sonar.tests=backend/aulafy-api-nest/src,frontend/aulafy-web/src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.angular/**,docs/**,database/**,**/*.config.js
sonar.javascript.lcov.reportPaths=backend/aulafy-api-nest/coverage/lcov.info

# Configurar SONAR_TOKEN como variable de entorno o GitHub Secret.
# No guardar tokens, claves ni credenciales en este archivo.
