name: Frontend Angular CI

on:
  push:
    branches:
      - develop
    paths:
      - "frontend/aulafy-web/**"
      - ".github/workflows/frontend-angular-ci.yml"
  pull_request:
    paths:
      - "frontend/aulafy-web/**"
      - ".github/workflows/frontend-angular-ci.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build Angular frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: frontend/aulafy-web/package-lock.json

      - name: Install dependencies
        working-directory: frontend/aulafy-web
        run: npm install

      - name: Build staging
        working-directory: frontend/aulafy-web
        run: npm run build:staging
